// <auto-generated />
namespace MehsDataUsers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class relationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relationship));
        
        string IMigrationMetadata.Id
        {
            get { return "201706290728467_relationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
